import { Inter } from "next/font/google";
import "./globals.css";
import { MusicPlayerProvider } from "../context/MusicPlayerContext";
import GlobalMusicPlayer from "../components/global-music-player";
import MessageBox from "../components/message-card";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create.xyz App",
	description: "Generated by create.xyz",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MusicPlayerProvider>
					<MessageBox />
					<MessageBox message="HI, Im Going TO Play Some Music, Is That Ok ?" />
					<GlobalMusicPlayer />
					{children}
				</MusicPlayerProvider>
			</body>
		</html>
	);
}
